In [1]:
# 2.3.6 Indexing Data

In [2]:
import numpy as np

In [3]:
# Create a two-dimensional array

A = np.array(np.arange(16)).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
# Get a value from the second row & third column

print(A[1,2])

6


In [9]:
# Get 2nd and 4th rows

print(A[[1,3]])

[[ 4  5  6  7]
 [12 13 14 15]]


In [10]:
# Get 1st and 3rd cols

print(A[:,[0,2]])

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


In [17]:
# Select submatrix from the 2nd & 4th rows and 1st & 3rd cols

print(A[[1,3]][:,[0,2]])

[[ 4  6]
 [12 14]]


In [45]:
# Select submatrix using np.ix_()
# np.ix_() returns a mesh object

idx = np.ix_([1,3],[0,2])
A[idx]

array([[ 4,  6],
       [12, 14]])

In [21]:
# Select submatrix using slice

A[1:4:2, 0:3:2]

array([[ 4,  6],
       [12, 14]])

In [22]:
# Boolean Indexing
# Create a vector of 0's, represented as Booleans

keep_rows = np.zeros(A.shape[0], bool)
keep_rows

array([False, False, False, False])

In [23]:
keep_rows[[1,3]] = True
keep_rows

array([False,  True, False,  True])

In [25]:
# True == 1
# False == 0

keep_rows == np.array([0, 1, 0, 1])

array([ True,  True,  True,  True])

In [32]:
# np.all(): True if all entries are True (or non-zero)

print(np.all(keep_rows))
print(np.all(np.array([1, 2, 3])))
print(np.all(np.array([0, 0, 0])))

False
True
False


In [35]:
# np.any(): True if any entry is True (or non-zero)

print(np.any(keep_rows))
print(np.any(np.array([4, 0, 0])))
print(np.any(np.array([0, 0, 0])))

True
True
False


In [42]:
# np.array([0, 1, 0, 1]) and keep_rows: np.array([False, True, False, True])
# return differnt sets of rows

# Returns 1st, 2nd, 1st, 2nd rows of A
print(A[np.array([0,1,0,1])], '\n')

# Returns 2nd and 4th rows of A
print(A[keep_rows])

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]] 

[[ 4  5  6  7]
 [12 13 14 15]]


In [49]:
# Get submatrix of A with np.ix_()
# 2nd & 4th rows and 1st & 3rd & 4th cols of A

keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [50]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]

array([[ 4,  6,  7],
       [12, 14, 15]])